### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by forart** [CraigWatt/vfo#68]
Hi there, 1st of all thanks for your cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [VIDEO](https://github.com/forart/HyMPS#-1) \ [Tools](https://github.com/forart/HyMPS/blob/main/VideoTools.md#--) \ [GUIs subsection](https://github.com/forart/HyMPS/blob/main/VideoTools.md#guis-)), can you please "standardize" the license for it ?

Although it may sounds like a minor aspect, a GH "uncompliant" license file causes an inconsistent generation of the relative badge:

![](https://flat.badgen.net/github/license/CraigWatt/vfo/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/CraigWatt/vfo/?label=LICENSE)

You can easily set a standardized license file through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by CraigWatt** [comment]
Hi forat,

Thanks for your input,  I'll get a chance to do this next week!  

Cheers,
Craig

**Comment by CraigWatt** [comment]
@forart , work is complete:
<img width="939" alt="Screenshot 2024-01-19 at 17 08 33" src="https://github.com/CraigWatt/vfo/assets/87949406/bd0c72e8-10a3-4fc0-9b75-bba7b17caccb">

Please close this issue if you are happy with this work.

Many thanks,
Craig

**Comment by forart** [comment]
Thanks a lot ! (1st position achieved)
